// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpjo4eiIVIPJncMyMlIjBJ0zSthG4wWgo',
    appId: '1:881487209485:web:dce807dbd838135ed76144',
    messagingSenderId: '881487209485',
    projectId: 'testproject-1c519',
    authDomain: 'testproject-1c519.firebaseapp.com',
    databaseURL: 'https://testproject-1c519-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testproject-1c519.firebasestorage.app',
    measurementId: 'G-WHVELXYVCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCST7_Ak7QUP2UwrBFYlPMQQXz3-pPlJpw',
    appId: '1:881487209485:android:08e391ceda880455d76144',
    messagingSenderId: '881487209485',
    projectId: 'testproject-1c519',
    databaseURL: 'https://testproject-1c519-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testproject-1c519.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEn7O2szKib-mVkRnalw-ZEuBDLSmDJAI',
    appId: '1:881487209485:ios:fd6ef632a8f04d61d76144',
    messagingSenderId: '881487209485',
    projectId: 'testproject-1c519',
    databaseURL: 'https://testproject-1c519-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testproject-1c519.firebasestorage.app',
    iosBundleId: 'com.example.karyawan2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEn7O2szKib-mVkRnalw-ZEuBDLSmDJAI',
    appId: '1:881487209485:ios:fd6ef632a8f04d61d76144',
    messagingSenderId: '881487209485',
    projectId: 'testproject-1c519',
    databaseURL: 'https://testproject-1c519-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testproject-1c519.firebasestorage.app',
    iosBundleId: 'com.example.karyawan2',
  );

}